const DEMO_UI_TOKEN="xyena-demo";const $=(id)=>document.getElementById(id);const esc=(v)=>String(v??"").replace(/[&<>'"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"})[c]);const money=(v)=>new Intl.NumberFormat("en-IN",{style:"currency",currency:"INR",maximumFractionDigits:2}).format(Number(v||0));const text=(id,v)=>{if($(id))$(id).textContent=v};
const tools=[["ledger.accounts.get_balance","Sensitive read"],["ledger.journals.get","Sensitive read"],["ledger.payments.get_status","Sensitive read"],["ledger.reconciliation.get","Sensitive read"],["ledger.disbursements.prepare","Prepare"],["ledger.disbursements.execute","Guardian approval"],["ledger.reversals.prepare","Prepare"],["ledger.reversals.execute","Reviewer + Guardian"]];
function render(d){const debit=d.journals.reduce((s,j)=>s+Number(j.total_debits),0),credit=d.journals.reduce((s,j)=>s+Number(j.total_credits),0);text("accountCount",d.accounts.length);text("journalCount",d.journals.length);text("paymentCount",d.payments.length);text("matchedCount",d.reconciliations.filter(r=>r.status==="MATCHED").length);text("auditCount",d.audit_event_count);text("receiptCount",d.settlement_receipt_count);text("debitTotal",money(debit));text("creditTotal",money(credit));text("tenantId",d.scope.tenant_id);
 if($("accountRows"))$("accountRows").innerHTML=d.accounts.map(a=>`<tr><td><strong>${esc(a.code)} · ${esc(a.name)}</strong><small>${esc(a.account_type)} · normal ${esc(a.normal_side)}</small></td><td><code>${esc(a.account_id)}</code></td><td class="right"><strong>${money(a.balance)}</strong></td><td>${a.version}</td><td><span class="status safe">${esc(a.status)}</span></td></tr>`).join("")||'<tr><td class="empty" colspan="5">No ledger accounts.</td></tr>';
 if($("journalRows"))$("journalRows").innerHTML=d.journals.map(j=>`<tr><td><code>${esc(j.journal_id)}</code><small>${esc(j.financing_case_id)}</small></td><td>${esc(j.entry_type)}</td><td class="right">${money(j.total_debits)}</td><td class="right">${money(j.total_credits)}</td><td><span class="status ${j.status==="POSTED"?"safe":"review"}">${esc(j.status)}</span></td></tr>`).join("")||'<tr><td class="empty" colspan="5">No journals have been prepared.</td></tr>';
 if($("paymentRows"))$("paymentRows").innerHTML=d.payments.map(p=>`<tr><td><code>${esc(p.payment_id)}</code><small>${esc(p.financing_case_id)}</small></td><td class="right">${money(p.amount)}</td><td><code>${esc(p.bank_reference||"—")}</code></td><td><span class="status ${p.status==="SETTLED"?"safe":"review"}">${esc(p.status)}</span></td></tr>`).join("")||'<tr><td class="empty" colspan="4">No payment instructions.</td></tr>';
 if($("reconciliationRows"))$("reconciliationRows").innerHTML=d.reconciliations.map(r=>`<tr><td><code>${esc(r.reconciliation_id)}</code></td><td><code>${esc(r.payment_id)}</code></td><td><code>${esc(r.settlement_receipt_id||"—")}</code></td><td class="right">${money(r.variance_amount)}</td><td><span class="status ${r.status==="MATCHED"?"safe":"review"}">${esc(r.status)}</span></td></tr>`).join("")||'<tr><td class="empty" colspan="5">No settlement has reached reconciliation.</td></tr>';
}
if($("toolGrid"))$("toolGrid").innerHTML=tools.map(([n,r])=>`<div class="tool"><code>${n}</code><small>${r}</small></div>`).join("");
async function load(token){try{const r=await fetch("/api/v1/demo/summary",{headers:{"X-Demo-Token":token}});if(!r.ok)throw new Error(r.status===401?"Dashboard token was not accepted.":`API returned ${r.status}.`);render(await r.json());sessionStorage.setItem("xyena-ledger-token",token);$("access")?.classList.add("connected");text("state","Dataset connected")}catch(e){text("message",e.message)}}
$("accessForm")?.addEventListener("submit",e=>{e.preventDefault();load($("token").value)});const saved=sessionStorage.getItem("xyena-ledger-token");if($("token"))$("token").value=saved||DEMO_UI_TOKEN;if(saved)load(saved)
